### ISSUE TITLE
How to get BOT ID of Telagram 

### ISSUE THREAD

**Issue by hasd-daniel** [ragedsparrow/splunk_telegram-alert-action#1]
Dear,
Could you help me how to get telegram BOT ID. it is bot token right? I was research on telegram document guide but do not  see any comment about telegram BotID.

**Comment by the-data-sherpa** [comment]
It is the Bot Authorization Token, correct.  I apologize if the wording in the Splunk app made it confusing, I'll correct it is a future push.  It's obtained after the new bot is created through Telegram's BotFather:

https://core.telegram.org/bots#6-botfather

**Comment by hasd-daniel** [comment]
Thank you so much.
